#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCK_FILE="$ROOT_DIR/mansu-operating-model/references/SOURCE_SKILL_LOCK.json"
CATALOG="$ROOT_DIR/mansu-operating-model/references/SOURCE_SKILL_CATALOG.md"
CURATOR="$ROOT_DIR/mansu-source-curator/SKILL.md"

test -f "$LOCK_FILE"

python3 -m json.tool "$LOCK_FILE" >/dev/null

grep -q '"id": "ouroboros"' "$LOCK_FILE"
grep -q '"id": "gstack"' "$LOCK_FILE"
grep -q '"id": "oh-my-codex-runtime"' "$LOCK_FILE"
grep -q '"id": "addyosmani-agent-skills"' "$LOCK_FILE"
grep -q '"id": "voltagent-awesome-design-md"' "$LOCK_FILE"
grep -q '"id": "nexu-open-design"' "$LOCK_FILE"
grep -q '"last_checked": "2026-05-16"' "$LOCK_FILE"
grep -q '"skill_inventory"' "$LOCK_FILE"
grep -q '"tracked_capabilities"' "$LOCK_FILE"
grep -q 'skills/seed' "$LOCK_FILE"
grep -q 'skills/pm' "$LOCK_FILE"
grep -q 'skills/brownfield' "$LOCK_FILE"
grep -q 'skills/ralph' "$LOCK_FILE"
grep -q 'skills/publish' "$LOCK_FILE"
grep -q 'ouroboros setup --runtime' "$LOCK_FILE"
grep -q 'inventory_warning' "$LOCK_FILE"
grep -q 'Exclude mansu-\*, gstack-\*' "$LOCK_FILE"
grep -q 'gstack-context-save' "$LOCK_FILE"
grep -q 'gstack-context-restore' "$LOCK_FILE"
grep -q 'planning-and-task-breakdown' "$LOCK_FILE"
grep -q 'shipping-and-launch' "$LOCK_FILE"
grep -q 'VoltAgent/awesome-design-md' "$LOCK_FILE"
grep -q 'DESIGN.md format' "$LOCK_FILE"
grep -q 'Visual Theme & Atmosphere' "$LOCK_FILE"
grep -q 'Color Palette & Roles' "$LOCK_FILE"
grep -q 'Typography Rules' "$LOCK_FILE"
grep -q 'Component Stylings' "$LOCK_FILE"
grep -q 'Layout Principles' "$LOCK_FILE"
grep -q 'Depth & Elevation' "$LOCK_FILE"
grep -q "Do's and Don'ts" "$LOCK_FILE"
grep -q 'Responsive Behavior' "$LOCK_FILE"
grep -q 'Agent Prompt Guide' "$LOCK_FILE"
grep -q '"inventory_count": 71' "$LOCK_FILE"
grep -q 'Local file count under design-md is 71' "$LOCK_FILE"
grep -q 'https://github.com/nexu-io/open-design' "$LOCK_FILE"
grep -q 'open-design-v0.4.1 release snapshot' "$LOCK_FILE"
grep -q 'b1121c0' "$LOCK_FILE"
grep -q 'pnpm install' "$LOCK_FILE"
grep -q 'pnpm tools-dev' "$LOCK_FILE"
grep -q 'only local lifecycle entry point' "$LOCK_FILE"
! grep -q 'pnpm dev:all' "$LOCK_FILE"
grep -q 'agent-native design workflow' "$LOCK_FILE"
grep -q 'Turn-1 discovery form' "$LOCK_FILE"
grep -q 'visual direction picker' "$LOCK_FILE"
grep -q 'artifact-first rendering loop' "$LOCK_FILE"
grep -q 'anti-AI-slop checklist' "$LOCK_FILE"
grep -q 'P0/P1/P2 gates' "$LOCK_FILE"

grep -q 'SOURCE_SKILL_LOCK.json' "$CATALOG"
grep -q 'SOURCE_SKILL_LOCK.json' "$CURATOR"
grep -q 'adapter-owned skill roots' "$CURATOR"
grep -q 'Exclude `mansu-\*`, `gstack-\*`' "$CURATOR"

echo "mansu source lock OK"
