#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FILE="$ROOT_DIR/mansu-help/SKILL.md"
OPENAI_YAML="$ROOT_DIR/mansu-help/agents/openai.yaml"
README_FILE="$ROOT_DIR/README.md"
README_KO_FILE="$ROOT_DIR/README.ko.md"

test -f "$FILE"
test -f "$OPENAI_YAML"
test -f "$README_FILE"
test -f "$README_KO_FILE"

grep -q '^name: mansu-help$' "$FILE"
grep -q '^description: Beginner-friendly Mansu triage and route recommendation workflow' "$FILE"
grep -q '^## Core promise$' "$FILE"
grep -q '^## Triage posture$' "$FILE"
grep -q '^## Minimal questions$' "$FILE"
grep -q '^## Route selector$' "$FILE"
grep -q '^## Beginner shortcuts$' "$FILE"
grep -q '^## Recommended answer shape$' "$FILE"
grep -q '^## Copy-paste prompt examples$' "$FILE"
grep -q '^## Safety$' "$FILE"
grep -q 'Beginner-friendly' "$FILE"
grep -q 'Ask only the minimum questions' "$FILE"
grep -q 'Recommend one best route' "$FILE"
grep -q 'Do not lead with internal words' "$FILE"
grep -q 'First response rule' "$FILE"
grep -q 'a short useful answer is better than a complete map' "$FILE"
grep -q 'copy-paste prompt' "$FILE"
grep -q '처음인데 뭐 해야 해' "$FILE"
grep -q '아이디어가 생겼어' "$FILE"
grep -q '웹앱 만들고 싶어' "$FILE"
grep -q 'new idea / new product definition' "$FILE"
grep -q '새 프로젝트 시작하고 싶어' "$FILE"
grep -q '기능 만들고 싶어' "$FILE"
grep -q 'New idea, new app, new webapp, or new product language takes precedence' "$FILE"
grep -q '현재 phase PLAN.md가 없으면 구현으로 가지 말고 먼저 mansu-project-start로 돌려줘' "$FILE"
grep -q 'mansu-setting' "$FILE"
grep -q 'mansu-setting source-check' "$FILE"
grep -q 'Source health check:' "$FILE"
grep -q '설치, 업데이트, sync, 파일 수정은 하지 말고' "$FILE"
grep -q 'Green/Yellow/Red' "$FILE"
grep -q 'mansu-source-curator curate' "$FILE"
grep -q 'mansu-project-start' "$FILE"
grep -q 'mansu-operating-model' "$FILE"
grep -q 'mansu-tdd-total' "$FILE"
grep -q 'mansu-debug-rootcause' "$FILE"
grep -q 'mansu-web-verify' "$FILE"
grep -q 'mansu-ship-release' "$FILE"
grep -q 'default to read-only diagnosis first' "$FILE"
grep -q 'Do not hide uncertainty' "$FILE"

grep -q '^interface:$' "$OPENAI_YAML"
grep -q 'display_name: "Mansu Help"' "$OPENAI_YAML"
grep -q 'short_description: "Beginner-friendly Mansu route helper"' "$OPENAI_YAML"
grep -q 'default_prompt: "Use \$mansu-help' "$OPENAI_YAML"
grep -q 'beginner-friendly Korean' "$OPENAI_YAML"
grep -q 'copy-paste prompt' "$OPENAI_YAML"

grep -q '| `mansu-help` |' "$README_FILE"
grep -q 'Zero-to-PLAN minimum gate' "$README_FILE"
grep -q 'scripts/validate_mansu_help.sh' "$README_FILE"
grep -q '\[mansu-help\]' "$README_FILE"
grep -q '| `mansu-help` |' "$README_KO_FILE"
grep -q 'Zero-to-PLAN minimum gate' "$README_KO_FILE"
grep -q '초보자' "$README_KO_FILE"
grep -q '무엇을 해야 할지' "$README_KO_FILE"
grep -q 'scripts/validate_mansu_help.sh' "$README_KO_FILE"
grep -q '\[mansu-help\]' "$README_KO_FILE"

echo "mansu-help structure OK"
