#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FILE="$ROOT_DIR/mansu-project-start/SKILL.md"
OPENAI_YAML="$ROOT_DIR/mansu-project-start/agents/openai.yaml"

test -f "$FILE"
test -f "$OPENAI_YAML"

grep -q '^name: mansu-project-start$' "$FILE"
grep -q '^description: Zero-to-PLAN project kickoff workflow' "$FILE"
grep -q '^## Core promise$' "$FILE"
grep -q '^## Orchestration posture$' "$FILE"
grep -q '^## Project-start route selector$' "$FILE"
grep -q '^## Research discipline$' "$FILE"
grep -q '^## Workflow$' "$FILE"
grep -q '^## Required handoff to implementation$' "$FILE"
grep -q 'GitHub, Reddit, and' "$FILE"
grep -q 'Threads' "$FILE"
grep -q 'official docs, source files, changelogs, release notes' "$FILE"
grep -q 'DOCUMENT_CREATION_ORDER.md' "$FILE"
grep -q 'CODE_CONSTRUCTION_ORDER.md' "$FILE"
grep -q 'gstack-autoplan' "$FILE"
grep -q 'gstack-plan-' "$FILE"
grep -q 'Do not reimplement strong source routes inside Mansu' "$FILE"
grep -q 'thin project-start orchestrator' "$FILE"
grep -q 'delegate fuzzy project definition to Ouroboros when it is the best available route' "$FILE"
grep -q 'gstack, Oh My, addyosmani, or another stronger source route' "$FILE"
grep -q 'avoid asking duplicate questions' "$FILE"
grep -q 'ask the user only when a missing answer materially changes scope' "$FILE"
grep -q 'translate source artifacts into Mansu-owned documents' "$FILE"
grep -q 'choose the smallest source route that fits' "$FILE"
grep -q 'Do not emulate a source route manually' "$FILE"
grep -q 'Ouroboros `brownfield`; addyosmani `context-engineering`' "$FILE"
grep -q 'Ouroboros `interview`; `gstack-office-hours`; addyosmani `idea-refine`' "$FILE"
grep -q 'gstack-office-hours' "$FILE"
grep -q 'addyosmani `idea-refine`' "$FILE"
grep -q 'Ouroboros `pm`' "$FILE"
grep -q 'Ouroboros `seed`' "$FILE"
grep -q 'Oh My `research` / `deepsearch`' "$FILE"
grep -q 'gstack-autoplan' "$FILE"
grep -q 'gstack-design-shotgun' "$FILE"
grep -q 'Ouroboros `evaluate` / `qa`' "$FILE"
grep -q 'Ouroboros `evolve` / `ralph`' "$FILE"
grep -q 'Ouroboros' "$FILE"
grep -q 'Seed/Ledger' "$FILE"
grep -q 'Ouroboros `auto --skip-run`' "$FILE"
grep -q 'do not start implementation from project-start' "$FILE"
grep -q 'project roadmap/phase order' "$FILE"
grep -q '^## Roadmap vs PLAN.md boundary$' "$FILE"
grep -q 'The project roadmap belongs in the spec/TDR/design layer' "$FILE"
grep -q 'belongs to the active phase' "$FILE"
grep -q 'Project-start does not build inside this skill' "$FILE"
grep -q 'included implementation' "$FILE"
grep -q 'Ouroboros artifacts used' "$FILE"
grep -q 'upstream source-of-truth artifacts' "$FILE"
grep -q 'project roadmap or phase order artifact' "$FILE"
grep -q 'Source skills skipped:' "$FILE"
grep -q 'Upstream source-of-truth artifacts and paths:' "$FILE"
grep -q 'Ouroboros skipped reason:' "$FILE"
grep -q 'References inspected with date/version/source evidence:' "$FILE"
grep -q 'Project roadmap / phase order artifact:' "$FILE"
grep -q 'Locked decisions and why:' "$FILE"
grep -q 'Open questions and blocker status:' "$FILE"
grep -q 'Current phase goal:' "$FILE"
grep -q 'Ordered vertical slices:' "$FILE"
grep -q 'Gate mapping:' "$FILE"
grep -q 'Validation commands:' "$FILE"
grep -q 'Worklog target:' "$FILE"
grep -q 'Recommended mansu-tdd-total modes:' "$FILE"
grep -q 'gate mapping' "$FILE"
grep -q 'mansu-tdd-total' "$FILE"

grep -q '^interface:$' "$OPENAI_YAML"
grep -q 'display_name: "Mansu Project Start"' "$OPENAI_YAML"
grep -q 'short_description: "Zero-to-PLAN project kickoff"' "$OPENAI_YAML"
grep -q 'default_prompt: "Use \$mansu-project-start' "$OPENAI_YAML"
grep -q 'thin project-start orchestrator' "$OPENAI_YAML"
grep -q 'choose the best source route for the situation across Ouroboros, gstack, Oh My, addyosmani' "$OPENAI_YAML"
grep -q 'avoid duplicating selected source logic' "$OPENAI_YAML"
grep -q 'source artifacts' "$OPENAI_YAML"
grep -q 'keep source artifacts, research, spec, TDR, design direction, and project roadmap outside PLAN.md' "$OPENAI_YAML"
grep -q 'derive only the current phase execution-ready PLAN.md' "$OPENAI_YAML"

echo "mansu-project-start structure OK"
