#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FILE="$ROOT_DIR/mansu-operating-model/references/SOURCE_SKILL_COMPOSITION.md"
CATALOG="$ROOT_DIR/mansu-operating-model/references/SOURCE_SKILL_CATALOG.md"
CODE_ORDER="$ROOT_DIR/mansu-operating-model/references/CODE_CONSTRUCTION_ORDER.md"

test -f "$FILE"

grep -q '^# Mansu Source Skill Composition' "$FILE"
grep -q 'Define -> Plan -> Build -> Verify -> Review -> Ship' "$FILE"
grep -q '`mansu-debug` is a public special-purpose interrupt route' "$FILE"
grep -q 'interview-me' "$FILE"
grep -q 'Ouroboros' "$FILE"
grep -q 'Use Ouroboros first for new products, apps, repos, major feature families, or fuzzy ideas' "$FILE"
grep -q 'Start with public `mansu-1define`; it discovers and uses Ouroboros `interview` first when available' "$FILE"
grep -q 'office-hours' "$FILE"
grep -q 'Requirements/Spec -> Architecture -> Design Direction -> Implementation Roadmap' "$FILE"
grep -q 'Open Design' "$FILE"
grep -q 'VoltAgent/awesome-design-md' "$FILE"
grep -q 'gstack-design-shotgun' "$FILE"
grep -q 'mansu-tdd-total' "$FILE"
grep -q 'Verify proves behavior' "$FILE"
grep -q 'Review judges quality' "$FILE"
grep -q 'continuous sequence by default when verification passes' "$FILE"
grep -q 'Passing Verify hands off to Review by default' "$FILE"
grep -q 'LazyCodex is the Codex-side route for OMO execution patterns' "$FILE"
grep -q 'must not appear as a phase source' "$FILE"
grep -q 'Public lifecycle route names are numbered: `mansu-1define` through' "$FILE"
grep -q 'compatibility implementation names only' "$FILE"
grep -q '| `mansu-1define` |' "$FILE"
grep -q '| `mansu-2plan` |' "$FILE"
grep -q '| `mansu-3build` |' "$FILE"
grep -q '| `mansu-4verify` |' "$FILE"
grep -q '| `mansu-5review` |' "$FILE"
grep -q '| `mansu-6ship` |' "$FILE"
grep -q 'Backed by `mansu-define`' "$FILE"
grep -q 'Backed by `mansu-plan`' "$FILE"
grep -q 'Backed by `mansu-build`' "$FILE"
grep -q 'Backed by `mansu-verify`' "$FILE"
grep -q 'Backed by `mansu-review`' "$FILE"
grep -q 'Backed by `mansu-ship`' "$FILE"
! grep -Eq '^\| `mansu-(define|plan|build|verify|review|ship)` \|' "$FILE"
! grep -Eq -- '- .*-> `mansu-(define|plan|build|verify|review|ship)`([`[:space:]/.,]|$)' "$FILE"
grep -q 'Fuzzy new product: public `mansu-1define` -> Ouroboros' "$FILE"
grep -q 'Clear new project: public `mansu-1define` -> Ouroboros' "$FILE"
! grep -q 'Fuzzy new product: addyosmani `interview-me`' "$FILE"
! grep -q -- '-> `mansu-2plan`' "$FILE"

grep -q 'SOURCE_SKILL_COMPOSITION.md' "$CATALOG"
grep -q 'SOURCE_SKILL_COMPOSITION.md' "$CODE_ORDER"
grep -q 'Use public routes `mansu-1define` and then `mansu-2plan`' "$CATALOG"
grep -q 'Hand off to public route `mansu-3build`' "$CATALOG"
grep -q 'Use public route `mansu-4verify`' "$CATALOG"
grep -q 'Use public route `mansu-6ship`' "$CATALOG"
! grep -Eiq 'Use[[:space:]]+`mansu-define`[[:space:]]+and[[:space:]]+then[[:space:]]+`mansu-plan`' "$CATALOG"
! grep -Eiq 'use[[:space:]]+`mansu-define`' "$CATALOG"
! grep -Eiq 'Hand off to[[:space:]]+`mansu-build`' "$CATALOG"
! grep -Eiq 'For non-trivial work,[[:space:]]+use[[:space:]]+`mansu-build`' "$CATALOG"
! grep -Eiq 'Use[[:space:]]+`mansu-verify`' "$CATALOG"
! grep -Eiq 'Use[[:space:]]+`mansu-ship`' "$CATALOG"

! grep -q 'LazyCodex/OMO Codex plugin as preferred Codex transport' "$CODE_ORDER"
