#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FILE="$ROOT_DIR/mansu-project-start/SKILL.md"
OPENAI_YAML="$ROOT_DIR/mansu-project-start/agents/openai.yaml"

test -f "$FILE"
test -f "$OPENAI_YAML"

grep -q '^name: mansu-project-start$' "$FILE"
grep -q '^description: Zero-to-PLAN project kickoff workflow' "$FILE"
grep -q '^## Core promise$' "$FILE"
grep -q '^## Orchestration posture$' "$FILE"
grep -q '^## Project-start route selector$' "$FILE"
grep -q '^## Research discipline$' "$FILE"
grep -q '^## Workflow$' "$FILE"
grep -q '^## Required handoff to phase execution$' "$FILE"
grep -q 'GitHub, Reddit, and' "$FILE"
grep -q 'Threads' "$FILE"
grep -q 'official docs, source files, changelogs, release notes' "$FILE"
grep -q 'DOCUMENT_CREATION_ORDER.md' "$FILE"
grep -q 'CODE_CONSTRUCTION_ORDER.md' "$FILE"
grep -q 'gstack-autoplan' "$FILE"
grep -q 'gstack-plan-' "$FILE"
grep -q 'Do not reimplement strong source routes inside Mansu' "$FILE"
grep -q 'thin project-start orchestrator' "$FILE"
grep -q 'delegate fuzzy project definition to Ouroboros when it is the best available route' "$FILE"
grep -q 'gstack, Oh My, addyosmani, or another stronger source route' "$FILE"
grep -q 'avoid asking duplicate questions' "$FILE"
grep -q 'ask the user only when a missing answer materially changes scope' "$FILE"
grep -q 'translate source artifacts into Mansu-owned documents' "$FILE"
grep -q 'choose the smallest source route that fits' "$FILE"
grep -q 'Do not emulate a source route manually' "$FILE"
grep -q 'reference-only sources rather than executable routes' "$FILE"
grep -q 'not invoked, installed, or treated as a runtime skill' "$FILE"
grep -q 'Ouroboros `brownfield`; addyosmani `context-engineering`' "$FILE"
grep -q 'Ouroboros `interview`; `gstack-office-hours`; addyosmani `idea-refine`' "$FILE"
grep -q 'gstack-office-hours' "$FILE"
grep -q 'addyosmani `idea-refine`' "$FILE"
grep -q 'Ouroboros `pm`' "$FILE"
grep -q 'Ouroboros `seed`' "$FILE"
grep -q 'Oh My `research` / `deepsearch`' "$FILE"
grep -q 'gstack-autoplan' "$FILE"
grep -q 'gstack-design-shotgun' "$FILE"
grep -q 'VoltAgent/awesome-design-md' "$FILE"
grep -q 'reference only, not an execution route' "$FILE"
grep -q 'DESIGN.md reference / visual taste' "$FILE"
grep -q 'Design references used:' "$FILE"
grep -q 'DESIGN.md status:' "$FILE"
grep -q 'visual atmosphere, color roles, typography' "$FILE"
grep -q 'Ouroboros `evaluate` / `qa`' "$FILE"
grep -q 'Ouroboros `evolve` / `ralph`' "$FILE"
grep -q 'Ouroboros' "$FILE"
grep -q 'Seed/Ledger' "$FILE"
grep -q 'Ouroboros `auto --skip-run`' "$FILE"
grep -q 'do not start implementation from project-start' "$FILE"
grep -q 'setup/help route only when missing setup blocks the next project-definition' "$FILE"
grep -q 'run a lightweight kickoff, record setup uncertainty' "$FILE"
grep -q '^## Zero-to-PLAN minimum gate$' "$FILE"
grep -q '^## Expand when useful$' "$FILE"
grep -q 'Use this as a flexible gate, not a form-filling ritual' "$FILE"
grep -q 'Purpose: what are we making' "$FILE"
grep -q 'User/problem: who has the problem' "$FILE"
grep -q 'Evidence: what source route artifacts' "$FILE"
grep -q 'Assumptions: which unsupported guesses' "$FILE"
grep -q 'Direction: what product, technical, architecture' "$FILE"
grep -q 'Order: what are the large-grain phases' "$FILE"
grep -q 'Execution bridge: where is the current phase `PLAN.md`' "$FILE"
grep -q 'ordered slices, validation path, gate mapping, and `mansu-tdd-total` mode hints' "$FILE"
grep -q 'Do not jump into slice implementation' "$FILE"
grep -q 'Market, adoption, or taste risk' "$FILE"
grep -q 'Technical freshness risk' "$FILE"
grep -q 'Architecture or data risk' "$FILE"
grep -q 'UI risk' "$FILE"
grep -q 'Expensive or durable decision' "$FILE"
grep -q 'Expansion decisions must name the risk/ambiguity class' "$FILE"
grep -q 'DOCUMENT_CREATION_ORDER.md` artifact choice' "$FILE"
grep -q 'Do not create documents just to satisfy ceremony' "$FILE"
grep -q '^## Reference artifact defaults$' "$FILE"
grep -q 'docs/research/{topic-slug}.md' "$FILE"
grep -q 'docs/specs/{project-or-feature-slug}.md' "$FILE"
grep -q 'docs/technical/{project-or-feature-slug}.md' "$FILE"
grep -q '`PLAN.md` should link to research/spec/TDR/design artifacts' "$FILE"
grep -q 'project roadmap/phase order' "$FILE"
grep -q '^## Roadmap vs PLAN.md boundary$' "$FILE"
grep -q 'The project roadmap belongs in the spec/TDR/design layer' "$FILE"
grep -q 'belongs to the active phase' "$FILE"
grep -q 'does not own slice implementation' "$FILE"
grep -q 'owns the selected phase' "$FILE"
grep -q 'Project-start must not implement the slices itself' "$FILE"
grep -q 'the next owner is `mansu-tdd-total`' "$FILE"
grep -q 'Ouroboros artifacts used' "$FILE"
grep -q 'upstream source-of-truth artifacts' "$FILE"
grep -q 'project roadmap or phase order artifact' "$FILE"
grep -q 'Source skills skipped:' "$FILE"
grep -q 'Upstream source-of-truth artifacts and paths:' "$FILE"
grep -q 'Ouroboros skipped reason:' "$FILE"
grep -q 'References inspected with date/version/source evidence:' "$FILE"
grep -q 'Minimum gate status:' "$FILE"
grep -q -- '- Purpose:' "$FILE"
grep -q -- '- User/problem:' "$FILE"
grep -q -- '- Evidence:' "$FILE"
grep -q -- '- Assumptions:' "$FILE"
grep -q -- '- Direction:' "$FILE"
grep -q -- '- Order:' "$FILE"
grep -q -- '- Execution bridge:' "$FILE"
grep -q 'Expanded artifacts used/skipped:' "$FILE"
grep -q 'Project roadmap / phase order artifact:' "$FILE"
grep -q "Write the report in the user's language or the project's default language" "$FILE"
grep -q 'Field labels may stay canonical' "$FILE"
grep -q 'Locked decisions and why:' "$FILE"
grep -q 'Open questions and blocker status:' "$FILE"
grep -q 'Current phase goal:' "$FILE"
grep -q 'Ordered vertical slices:' "$FILE"
grep -q 'Gate mapping:' "$FILE"
grep -q 'Validation commands:' "$FILE"
grep -q 'Worklog target:' "$FILE"
grep -q 'Recommended mansu-tdd-total modes:' "$FILE"
grep -q 'gate mapping' "$FILE"
grep -q 'mansu-tdd-total' "$FILE"

grep -q '^interface:$' "$OPENAI_YAML"
grep -q 'display_name: "Mansu Project Start"' "$OPENAI_YAML"
grep -q 'short_description: "Zero-to-PLAN project kickoff"' "$OPENAI_YAML"
grep -q 'default_prompt: "Use \$mansu-project-start' "$OPENAI_YAML"
grep -q 'thin project-start orchestrator' "$OPENAI_YAML"
grep -q 'VoltAgent/awesome-design-md as DESIGN.md reference-only input' "$OPENAI_YAML"
grep -q 'avoid duplicating selected source logic' "$OPENAI_YAML"
grep -q 'satisfy the Zero-to-PLAN minimum gate before handoff' "$OPENAI_YAML"
grep -q 'purpose, user/problem, evidence, assumptions, direction, order, and execution bridge' "$OPENAI_YAML"
grep -q 'source artifacts' "$OPENAI_YAML"
grep -q 'keep source artifacts, research, spec, TDR, DESIGN.md/design direction, and project roadmap outside PLAN.md' "$OPENAI_YAML"
grep -q 'derive the current phase execution-ready PLAN.md' "$OPENAI_YAML"
grep -q 'ordered slices, validation path, gate mapping, and mansu-tdd-total mode hints' "$OPENAI_YAML"
grep -q 'hand that phase to \$mansu-tdd-total for slice-level planning, implementation, review, QA, and checkpoint' "$OPENAI_YAML"

echo "mansu-project-start structure OK"
