#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FILE="$ROOT_DIR/mansu-manual/SKILL.md"
OPENAI_YAML="$ROOT_DIR/mansu-manual/agents/openai.yaml"
OPEN_SCRIPT="$ROOT_DIR/mansu-manual/scripts/open-manual.sh"
README_FILE="$ROOT_DIR/README.md"
HTML_FILE="$ROOT_DIR/docs/mansu-manual.html"
SOURCE_LOCK="$ROOT_DIR/mansu-operating-model/references/SOURCE_SKILL_LOCK.json"

assert_contains() {
  local pattern="$1"
  local file="$2"
  grep -q "$pattern" "$file"
}

assert_not_contains() {
  local pattern="$1"
  local file="$2"
  ! grep -q "$pattern" "$file"
}

assert_count_ge() {
  local pattern="$1"
  local file="$2"
  local expected="$3"
  local actual
  actual="$(grep -o "$pattern" "$file" | wc -l | tr -d ' ')"
  [ "$actual" -ge "$expected" ]
}

test -f "$FILE"
test -f "$OPENAI_YAML"
test -x "$OPEN_SCRIPT"
test -f "$README_FILE"
test -f "$HTML_FILE"
test -f "$SOURCE_LOCK"

source_lock_date="$(jq -r '.last_checked' "$SOURCE_LOCK")"
gstack_version="$(jq -r '.families[] | select(.id == "gstack") | .version' "$SOURCE_LOCK")"
gstack_commit="$(jq -r '.families[] | select(.id == "gstack") | .commit' "$SOURCE_LOCK")"
ouroboros_commit="$(jq -r '.families[] | select(.id == "ouroboros") | .commit' "$SOURCE_LOCK")"
design_commit="$(jq -r '.families[] | select(.id == "voltagent-awesome-design-md") | .commit' "$SOURCE_LOCK")"

[ -n "$source_lock_date" ]
[ -n "$gstack_version" ]
[ -n "$gstack_commit" ]
[ -n "$ouroboros_commit" ]
[ -n "$design_commit" ]

grep -q '^name: mansu-manual$' "$FILE"
grep -q '^description: Open or point to the prebuilt beginner-friendly HTML manual' "$FILE"
grep -q '^## Core promise$' "$FILE"
grep -q '^## Manual path$' "$FILE"
grep -q '^## Workflow$' "$FILE"
grep -q '^## Manual maintenance requirements$' "$FILE"
grep -q '^## Beginner tone$' "$FILE"
grep -q '^## Validation$' "$FILE"
grep -q 'docs/mansu-manual.html' "$FILE"
grep -q 'single self-contained HTML manual' "$FILE"
grep -q 'Open the single self-contained HTML manual when the environment supports local HTML' "$FILE"
grep -q 'Open through `scripts/open-manual.sh` first' "$FILE"
grep -q 'When the user asks for `mansu-manual`, open this file first' "$FILE"
grep -q '^## Opener script$' "$FILE"
grep -q 'mansu-manual/scripts/open-manual.sh' "$FILE"
grep -q 'OPENED:{absolute-path}' "$FILE"
grep -q 'OPEN_UNAVAILABLE:{absolute-path}' "$FILE"
grep -q 'Run `mansu-manual/scripts/open-manual.sh` when available' "$FILE"
grep -q 'Showing or opening the manual should not modify files' "$FILE"
grep -q 'development process flow first' "$FILE"
grep -q 'top-level `mansu-\*` skills in their own `Mansu Skill` tab' "$FILE"
grep -q 'without duplicating Mansu' "$FILE"
grep -q '^## Agent self-orientation$' "$FILE"
grep -q 'lightweight agent routing map' "$FILE"
grep -q 'When an agent is choosing which Mansu route to use' "$FILE"
grep -q '`mansu-0help`, `mansu-0manual`, `mansu-9setup`, or `mansu-source-curator`' "$FILE"
grep -q 'If a specific execution skill has already been selected, its own `SKILL.md`' "$FILE"
grep -q 'Do not require every Mansu skill to read the manual' "$FILE"
grep -q 'the `에이전트 안내` tab exists' "$FILE"
grep -q 'the `Mansu Skill` tab exists' "$FILE"
grep -q 'the `스킬 카탈로그` tab exists and is grouped by source family first, then purpose' "$FILE"
grep -q 'Codex -> LazyCodex / OMO plus legacy `omx` compatibility, OpenCode/Hermes -> `omo`, Claude Code -> `omc`' "$FILE"
grep -q 'development process tab still points beginners to `mansu-0help` first' "$FILE"
grep -q 'Skill cards for every top-level `mansu-\*` skill' "$FILE"
grep -q 'Agent guide tab explaining how agents should route Mansu work before acting' "$FILE"
grep -q 'Skill catalog grouped by external/source family first, then purpose' "$FILE"
grep -q 'static artifact' "$FILE"
grep -q 'Whenever a `mansu-\*` skill is added' "$FILE"

grep -q '^interface:$' "$OPENAI_YAML"
grep -q 'display_name: "Mansu Manual"' "$OPENAI_YAML"
grep -q 'short_description: "Open prebuilt Mansu HTML manual"' "$OPENAI_YAML"
grep -q 'default_prompt: "Use \$mansu-manual' "$OPENAI_YAML"
grep -q 'running mansu-manual/scripts/open-manual.sh first' "$OPENAI_YAML"
grep -q 'then report the OPENED path' "$OPENAI_YAML"
grep -q 'prebuilt beginner-friendly Korean HTML guide' "$OPENAI_YAML"
grep -q 'agent guidance' "$OPENAI_YAML"
grep -q 'family-first skill catalog' "$OPENAI_YAML"
grep -q 'basic route examples' "$OPENAI_YAML"
! grep -q 'basic prompts' "$OPENAI_YAML"

grep -q 'OPENED:' "$OPEN_SCRIPT"
grep -q 'OPEN_UNAVAILABLE:' "$OPEN_SCRIPT"
grep -q 'mansu-manual.html' "$OPEN_SCRIPT"
grep -q 'command -v open' "$OPEN_SCRIPT"

grep -q 'Mansu Manual' "$HTML_FILE"
grep -q 'Mansu AgenticDev Manual' "$HTML_FILE"
grep -q 'Mansu AgenticDev는 AI 에이전트와 함께 소프트웨어를 계획하고, 만들고, 검증하고, 출시하기 위한 오케스트레이션 시스템입니다' "$HTML_FILE"
grep -q 'data-manual-purpose="lifecycle-route-map"' "$HTML_FILE"
grep -q 'data-manual-version="2026-06-08"' "$HTML_FILE"
grep -q 'data-manual-section="hero"' "$HTML_FILE"
grep -q 'data-manual-section="top-level-routes"' "$HTML_FILE"
grep -q 'SUIT Variable' "$HTML_FILE"
grep -q 'Gowun Batang' "$HTML_FILE"
grep -q -- '--font-body' "$HTML_FILE"
grep -q -- '--font-display' "$HTML_FILE"
grep -q 'Mansu의 개발 프로세스는 AI 에이전트가 더 자율적으로 코드를 만들 수 있도록 일을 정의, 계획, 구현, 검증, 리뷰, 배포 순서로 나누는 흐름입니다' "$HTML_FILE"
grep -q '각 단계가 끝나면 다음에 쓸 Mansu 스킬을 마지막에 안내합니다' "$HTML_FILE"
grep -q '정의가 끝나면 다음 단계로 <code>mansu-2plan</code>을 안내합니다' "$HTML_FILE"
grep -q '계획이 끝나면 다음 단계로 <code>mansu-3build</code>를 안내합니다' "$HTML_FILE"
grep -q '구현이 끝나면 다음 단계로 <code>mansu-4verify</code>를 안내합니다' "$HTML_FILE"
grep -q '리뷰가 통과하면 다음 단계로 <code>mansu-6ship</code>을 안내합니다' "$HTML_FILE"
grep -q '<table class="lifecycle-table" aria-label="Mansu development lifecycle explanation">' "$HTML_FILE"
grep -q '<td><code>Define</code></td>' "$HTML_FILE"
grep -q '<td>무엇을 만들지 정하는 단계입니다. 해결하려는 문제, 필요한 기능, 만들 범위, 완료 기준을 명확히 합니다.</td>' "$HTML_FILE"
grep -q '<td>만든 기능이 의도한 대로 동작하는지 확인하는 단계입니다. 버튼, 입력값, 저장, 조회, 오류 상황 등을 직접 테스트합니다. 통과하면 기본적으로 Review로 이어집니다.</td>' "$HTML_FILE"
grep -q '원인 불명 문제가 생기면 <code>mansu-debug</code>로 잠시 멈춰 원인을 먼저 찾습니다' "$HTML_FILE"
grep -q 'class="phase is-interrupt" data-detail="debug" role="button" tabindex="0" aria-pressed="false"' "$HTML_FILE"
grep -q '<span>Interrupt Route</span>' "$HTML_FILE"
! grep -q '생애주기 보기' "$HTML_FILE"
! grep -q 'Mansu Skill 보기' "$HTML_FILE"
! grep -q 'class="hero-actions"' "$HTML_FILE"
grep -q '<span>Mansu Skill</span>' "$HTML_FILE"
grep -q '<pre>mansu-0help</pre>' "$HTML_FILE"
grep -q '<pre>mansu-1define</pre>' "$HTML_FILE"
grep -q '<pre>mansu-2plan</pre>' "$HTML_FILE"
grep -q '<pre>mansu-3build</pre>' "$HTML_FILE"
grep -q '<pre>mansu-4verify</pre>' "$HTML_FILE"
grep -q '<pre>mansu-5review</pre>' "$HTML_FILE"
grep -q '<pre>mansu-6ship</pre>' "$HTML_FILE"
grep -q '<pre>mansu-9setup</pre>' "$HTML_FILE"
! grep -q 'copy-paste prompt' "$HTML_FILE"
! grep -q '스킬명만 말해도 작동합니다' "$HTML_FILE"
! grep -q '기본 호출 + 선택 문장' "$HTML_FILE"
! grep -q '더 구체적으로:' "$HTML_FILE"
! grep -q '복붙 프롬프트' "$HTML_FILE"
! grep -q '붙여 넣을 프롬프트' "$HTML_FILE"
grep -q '개발 프로세스' "$HTML_FILE"
grep -q 'Mansu Skill</label>' "$HTML_FILE"
grep -q '스킬 카탈로그' "$HTML_FILE"
grep -q '에이전트 안내' "$HTML_FILE"
grep -q 'data-manual-panel="lifecycle"' "$HTML_FILE"
grep -q 'data-manual-panel="mansu-skill"' "$HTML_FILE"
grep -q 'data-manual-panel="agents"' "$HTML_FILE"
grep -q 'data-manual-panel="catalog"' "$HTML_FILE"
grep -q 'data-detail="setup"' "$HTML_FILE"
grep -q 'data-detail-card="setup"' "$HTML_FILE"
! grep -q 'data-detail="setting"' "$HTML_FILE"
! grep -q 'data-detail-card="setting"' "$HTML_FILE"
! grep -q 'id="panel-architecture"' "$HTML_FILE"
! grep -q '아키텍처 / 큰그림' "$HTML_FILE"
grep -q 'panel-agents' "$HTML_FILE"
grep -q 'data-agent-guide="routing-map-not-execution-instruction"' "$HTML_FILE"
grep -q 'data-agent-rule="manual-is-route-map"' "$HTML_FILE"
grep -q 'data-agent-rule="route-selection"' "$HTML_FILE"
grep -q 'data-agent-rule="route-source-skills"' "$HTML_FILE"
grep -q 'data-agent-rule="runtime-aware-setup"' "$HTML_FILE"
grep -q 'data-agent-rule="project-start-before-code"' "$HTML_FILE"
grep -q 'data-agent-rule="total-before-implementation"' "$HTML_FILE"
grep -q 'data-agent-rule="root-cause-before-fix"' "$HTML_FILE"
grep -q 'data-agent-rule="user-language-report"' "$HTML_FILE"
grep -q 'data-agent-rule="manual-is-maintenance-artifact"' "$HTML_FILE"
grep -A2 'data-agent-rule="route-source-skills"' "$HTML_FILE" | grep -q '직접 흉내 내지 말고 연결한다'
grep -A2 'data-agent-rule="runtime-aware-setup"' "$HTML_FILE" | grep -q '설치는 실행 환경에 맞춘다'
grep -A2 'data-agent-rule="project-start-before-code"' "$HTML_FILE" | grep -q '프로젝트 시작은 큰 설계부터'
grep -A3 'data-agent-rule="total-before-implementation"' "$HTML_FILE" | grep -q '구현은 build에서 시작한다'
grep -A2 'data-agent-rule="root-cause-before-fix"' "$HTML_FILE" | grep -q '버그는 원인 전 수정 금지'
grep -A2 'data-agent-rule="user-language-report"' "$HTML_FILE" | grep -q '마지막 보고는 사용자 언어로'
grep -A2 'data-agent-rule="manual-is-maintenance-artifact"' "$HTML_FILE" | grep -q '매뉴얼도 산출물이다'
grep -q '에이전트를 위한 Mansu 사용법' "$HTML_FILE"
grep -q 'Mansu는 모든 걸 직접 구현하는 스킬이 아니라' "$HTML_FILE"
grep -q 'Mansu 매뉴얼 스냅샷: 2026-06-08' "$HTML_FILE"
grep -q "Source lock checked: $source_lock_date" "$HTML_FILE"
grep -q "gstack: $gstack_version / $gstack_commit" "$HTML_FILE"
grep -q "Ouroboros: $ouroboros_commit" "$HTML_FILE"
grep -q "Design references: VoltAgent/awesome-design-md $design_commit" "$HTML_FILE"
grep -q 'Design workflow: Open Design / nexu-io/open-design' "$HTML_FILE"
grep -q 'panel-catalog' "$HTML_FILE"
grep -q 'Codex에서는 검증된 LazyCodex / OMO를 확인하고' "$HTML_FILE"
grep -q 'legacy <code>omx</code> 호환성도 별도로 봅니다' "$HTML_FILE"
grep -q '런타임 / 어댑터 준비' "$HTML_FILE"
grep -q 'runtime/host/OS detect' "$HTML_FILE"
grep -q 'Codex -> LazyCodex / OMO' "$HTML_FILE"
grep -q 'legacy omx' "$HTML_FILE"
grep -q 'OpenCode/Hermes -> omo' "$HTML_FILE"
grep -q 'Claude Code -> omc' "$HTML_FILE"
! grep -q '현재 lock에는 Codex용 omx runtime adapter가 확인되어 있습니다' "$HTML_FILE"
grep -q 'catalog-item' "$HTML_FILE"
grep -q 'Skill detail' "$HTML_FILE"
grep -q 'Ouroboros &gt; 프로젝트 정의' "$HTML_FILE"
grep -q 'data-catalog-role' "$HTML_FILE"
grep -q 'data-catalog-when' "$HTML_FILE"
grep -q 'data-catalog-process' "$HTML_FILE"
grep -q 'data-catalog-output' "$HTML_FILE"
grep -q 'catalog-detail-name' "$HTML_FILE"
grep -q 'catalog-detail-process' "$HTML_FILE"
grep -q 'catalog-detail-output' "$HTML_FILE"
grep -q '패밀리별 지도' "$HTML_FILE"
grep -q '용도별 빠른 찾기' "$HTML_FILE"
! grep -q '보조: 상황별 빠른 찾기' "$HTML_FILE"
! grep -q '<div class="catalog-items">[[:space:]]*</div>' "$HTML_FILE"
grep -q '먼저 큰 원천 패밀리를 고르고, 그 안의 역할 박스에서 실제 세부 스킬을 고릅니다' "$HTML_FILE"
grep -q 'gstack</code> → <code>계획/비평</code> → <code>gstack-autoplan</code>' "$HTML_FILE"
grep -q 'source-family' "$HTML_FILE"
grep -q 'source-groups' "$HTML_FILE"
grep -q 'source-group' "$HTML_FILE"
! grep -q 'data-source-family="mansu"' "$HTML_FILE"
grep -q 'data-source-family="ouroboros"' "$HTML_FILE"
grep -q 'data-source-family="gstack"' "$HTML_FILE"
grep -q 'data-source-family="open-design"' "$HTML_FILE"
grep -q 'data-source-family="design-md"' "$HTML_FILE"
grep -q 'data-source-family="oh-my"' "$HTML_FILE"
grep -q 'data-source-family="agent-skills"' "$HTML_FILE"
grep -q 'data-catalog-mode="secondary-shortcuts"' "$HTML_FILE"
assert_count_ge 'class="tab-input"' "$HTML_FILE" 4
assert_count_ge 'class="tab-panel"' "$HTML_FILE" 4
assert_count_ge 'class="source-family"' "$HTML_FILE" 5
assert_count_ge 'class="source-group"' "$HTML_FILE" 14
assert_count_ge 'class="detail-card' "$HTML_FILE" 9
assert_count_ge 'class="mansu-detail-card' "$HTML_FILE" 12
assert_count_ge 'class="skill-card ' "$HTML_FILE" 12
assert_count_ge 'class="catalog-item' "$HTML_FILE" 50
grep -q 'id="panel-lifecycle"' "$HTML_FILE"
grep -q 'id="panel-mansu-skill"' "$HTML_FILE"
grep -q 'id="panel-agents"' "$HTML_FILE"
grep -q 'id="panel-catalog"' "$HTML_FILE"
grep -q '<h2>Mansu Skill</h2>' "$HTML_FILE"
grep -q '직접 호출하는 스킬' "$HTML_FILE"
grep -q 'data-mansu-detail="mansu-help"' "$HTML_FILE"
grep -q 'id="mansu-0help"' "$HTML_FILE"
grep -q 'id="mansu-1define"' "$HTML_FILE"
grep -q 'id="mansu-2plan"' "$HTML_FILE"
grep -q 'id="mansu-3build"' "$HTML_FILE"
grep -q 'id="mansu-4verify"' "$HTML_FILE"
grep -q 'id="mansu-5review"' "$HTML_FILE"
grep -q 'id="mansu-6ship"' "$HTML_FILE"
grep -q 'id="mansu-9setup"' "$HTML_FILE"
grep -q 'id="mansu-0manual"' "$HTML_FILE"
grep -q 'data-mansu-detail="mansu-ship-release"' "$HTML_FILE"
grep -q 'data-mansu-detail-card="mansu-help"' "$HTML_FILE"
grep -q 'data-mansu-detail-card="mansu-ship-release"' "$HTML_FILE"
grep -q 'Source Health Check' "$HTML_FILE"
grep -q 'Green/Yellow/Red 상태와 승인 필요한 다음 행동' "$HTML_FILE"
grep -q 'Check → Decide → Mutate' "$HTML_FILE"
grep -q 'validator와 dry-run이 통과한 뒤에만 설치본' "$HTML_FILE"
grep -q 'routing impact report' "$HTML_FILE"
grep -q 'dry-run / validator evidence' "$HTML_FILE"
grep -q '산출물: 추천 Mansu 스킬' "$HTML_FILE"
grep -q '산출물: ship / hold verdict' "$HTML_FILE"
grep -q 'Ouroboros</h3>' "$HTML_FILE"
grep -q 'gstack</h3>' "$HTML_FILE"
grep -q 'Open Design</h3>' "$HTML_FILE"
grep -q 'callable design route' "$HTML_FILE"
grep -q 'Open Design setup' "$HTML_FILE"
grep -q 'Turn-1 discovery' "$HTML_FILE"
grep -q 'visual direction' "$HTML_FILE"
grep -q 'artifact loop' "$HTML_FILE"
grep -q 'anti-AI-slop' "$HTML_FILE"
grep -q 'Mansu가 직접 CLI/lifecycle 명령' "$HTML_FILE"
grep -q 'VoltAgent/awesome-design-md</h3>' "$HTML_FILE"
grep -q 'Oh My / OMO / OMC</h3>' "$HTML_FILE"
grep -q 'addyosmani/agent-skills</h3>' "$HTML_FILE"
grep -q 'DESIGN.md 작성 기준' "$HTML_FILE"
grep -q 'DESIGN.md format' "$HTML_FILE"
grep -q 'Visual Theme &amp; Atmosphere' "$HTML_FILE"
grep -q 'Color Palette &amp; Roles' "$HTML_FILE"
grep -q 'Typography Rules' "$HTML_FILE"
grep -q 'Component Stylings' "$HTML_FILE"
grep -q 'Layout Principles' "$HTML_FILE"
grep -q 'Depth &amp; Elevation' "$HTML_FILE"
grep -q 'Do/Don'\''t + Responsive + Prompt' "$HTML_FILE"
grep -q '실행 경로가 아니라 <code>DESIGN.md</code>를 만들 때 참고하는 디자인 레퍼런스 묶음입니다' "$HTML_FILE"
grep -q '프로젝트 고유의 <code>DESIGN.md</code>' "$HTML_FILE"
grep -q '프로젝트 정의' "$HTML_FILE"
grep -q '계획 / 비평' "$HTML_FILE"
grep -q '디자인 / UI' "$HTML_FILE"
grep -q '검증 / QA / 보안 / 성능' "$HTML_FILE"
grep -q '리뷰 / 출하 / 문서 / 학습' "$HTML_FILE"
grep -q '런타임 adapter' "$HTML_FILE"
grep -q '기획 / 문맥 / spec' "$HTML_FILE"
grep -q 'skills/interview' "$HTML_FILE"
grep -q 'skills/pm' "$HTML_FILE"
grep -q 'skills/seed' "$HTML_FILE"
grep -q 'skills/publish' "$HTML_FILE"
grep -q 'commands/setup' "$HTML_FILE"
grep -q 'seed-authoring' "$HTML_FILE"
grep -q 'gstack-autoplan' "$HTML_FILE"
grep -q 'gstack-office-hours' "$HTML_FILE"
grep -q 'gstack-plan-eng-review' "$HTML_FILE"
grep -q 'gstack-devex-review' "$HTML_FILE"
grep -q 'gstack-investigate' "$HTML_FILE"
grep -q 'gstack-land-and-deploy' "$HTML_FILE"
grep -q 'gstack-claude' "$HTML_FILE"
grep -q 'gstack-benchmark-models' "$HTML_FILE"
grep -q 'gstack-make-pdf' "$HTML_FILE"
grep -q 'gstack-pair-agent' "$HTML_FILE"
grep -q 'gstack-landing-report' "$HTML_FILE"
grep -q 'gstack-plan-tune' "$HTML_FILE"
grep -q 'gstack-checkpoint는 설치된 runtime이 아직 노출할 때만 legacy alias' "$HTML_FILE"
assert_not_contains 'gstack-context-save / gstack-context-restore / gstack-checkpoint' "$HTML_FILE"
grep -q 'research' "$HTML_FILE"
grep -q 'deepsearch' "$HTML_FILE"
grep -q 'debug' "$HTML_FILE"
grep -q 'ralph' "$HTML_FILE"
grep -q 'ultrawork' "$HTML_FILE"
grep -q '프로젝트 정의 / 큰 그림' "$HTML_FILE"
grep -q '계획 / 아키텍처 / 비평' "$HTML_FILE"
grep -q '디자인 / UI' "$HTML_FILE"
grep -q '검증 / QA / 브라우저' "$HTML_FILE"
grep -q '출하 / 문서 / 학습' "$HTML_FILE"
grep -q 'Mansu development lifecycle' "$HTML_FILE"
grep -q '<span class="pill">시작</span>' "$HTML_FILE"
grep -q '도구와 스킬을 준비한다' "$HTML_FILE"
grep -q 'mansu-9setup source-check' "$HTML_FILE"
grep -q '개발 프로세스 단계가 아니라 관리자용 source freshness 점검입니다' "$HTML_FILE"
grep -q 'drift가 확인되면 승인 후 <code>mansu-source-curator</code>' "$HTML_FILE"
grep -q '계획한 내용을 만든다' "$HTML_FILE"
grep -q '코드를 작성하고, 화면을 만들고, 데이터 저장이나 기능 동작을 구현합니다' "$HTML_FILE"
grep -q '내부 흐름' "$HTML_FILE"
grep -q '산출물' "$HTML_FILE"
grep -q 'function catalogProcessFor' "$HTML_FILE"
grep -q 'function catalogOutputFor' "$HTML_FILE"
grep -q 'function updateCatalogDetail' "$HTML_FILE"
grep -q '조합하는 원천' "$HTML_FILE"
grep -q 'route-list' "$HTML_FILE"
grep -q '현재 작업을 분류하고 바로 쓸 Mansu 스킬을 고릅니다' "$HTML_FILE"
grep -q '<code>mansu-1define</code>의 compatibility alias입니다' "$HTML_FILE"
grep -q 'Ouroboros <code>interview</code>/<code>pm</code>/<code>seed</code>/<code>brownfield</code>' "$HTML_FILE"
grep -q '초기 정의 phase 안에서 목적, 제품 정의, 장기 기억, 기존 코드베이스 파악을 깊게 만듭니다' "$HTML_FILE"
grep -q '큰 기능 순서' "$HTML_FILE"
grep -q '새 아이디어/새 앱/새 프로젝트/큰 기능군' "$HTML_FILE"
grep -q '현재 phase 실행 계획이 있으면 <code>mansu-3build</code>, 없으면 먼저 <code>mansu-1define</code>/<code>mansu-2plan</code>' "$HTML_FILE"
grep -q 'definition brief' "$HTML_FILE"
grep -q '목적, 사용자/문제, 근거, 가정, 방향, 순서, 실행 연결' "$HTML_FILE"
grep -Fq '<code>.omo/plans/*.md</code>' "$HTML_FILE"
grep -q 'project roadmap / phase order' "$HTML_FILE"
grep -q '전체 기능 순서는 spec/TDR/design layer에 남기고' "$HTML_FILE"
grep -q '<code>mansu-3build</code>가 내부 엔진으로 <code>mansu-tdd-total</code>을 사용해' "$HTML_FILE"
grep -q 'gstack-office-hours' "$HTML_FILE"
grep -q '사용자, 문제, wedge, MVP가 진짜인지 창업자 관점으로 압축합니다' "$HTML_FILE"
grep -q 'gstack-autoplan' "$HTML_FILE"
grep -q 'Oh My <code>research</code>/<code>deepsearch</code>' "$HTML_FILE"
grep -q 'Threads, Reddit, GitHub, 실제 레포를 뒤져 참고 프로젝트와 인사이트를 찾습니다' "$HTML_FILE"
grep -q 'addyosmani <code>spec-driven-development</code>' "$HTML_FILE"
grep -q 'gstack-browse' "$HTML_FILE"
grep -q '실제 브라우저를 열어 버튼, 폼, 화면 상태, 콘솔을 확인합니다' "$HTML_FILE"
grep -q 'diff 관점에서 회귀, 누락 테스트, 위험한 side effect를 찾습니다' "$HTML_FILE"
grep -q 'SOURCE_SKILL_LOCK.json' "$HTML_FILE"
! grep -q 'detail-trigger' "$HTML_FILE"
! grep -q '과정 보기' "$HTML_FILE"
grep -q 'class="phase is-active" data-detail="help" role="button" tabindex="0" aria-pressed="true"' "$HTML_FILE"
grep -q 'class="phase" data-detail="define" role="button" tabindex="0" aria-pressed="false"' "$HTML_FILE"
grep -q 'class="phase" data-detail="plan" role="button" tabindex="0" aria-pressed="false"' "$HTML_FILE"
grep -q 'class="phase" data-detail="build" role="button" tabindex="0" aria-pressed="false"' "$HTML_FILE"
grep -q 'class="phase" data-detail="verify" role="button" tabindex="0" aria-pressed="false"' "$HTML_FILE"
grep -q 'class="phase" data-detail="review" role="button" tabindex="0" aria-pressed="false"' "$HTML_FILE"
grep -q 'class="phase" data-detail="ship" role="button" tabindex="0" aria-pressed="false"' "$HTML_FILE"
! grep -q 'data-detail="maintenance"' "$HTML_FILE"
! grep -q 'data-detail-card="maintenance"' "$HTML_FILE"
! grep -q '<pre>mansu-9setup source-check</pre>' "$HTML_FILE"
grep -q 'data-detail-card="debug"' "$HTML_FILE"
grep -q 'const detailTriggers = document.querySelectorAll(".phase\[data-detail\]")' "$HTML_FILE"
grep -q 'const mansuDetailTriggers = document.querySelectorAll(".mansu-skill-card\[data-mansu-detail\]")' "$HTML_FILE"
grep -q 'function selectDetail(trigger)' "$HTML_FILE"
grep -q 'function selectMansuDetail(trigger)' "$HTML_FILE"
grep -q 'event.key === "Enter"' "$HTML_FILE"
grep -q 'event.key === " "' "$HTML_FILE"
grep -q 'data-detail="build"' "$HTML_FILE"
grep -q 'data-detail-card="build"' "$HTML_FILE"
grep -q 'data-detail-card="verify"' "$HTML_FILE"
grep -q 'data-detail-card="review"' "$HTML_FILE"
grep -q '통과하면 기본적으로 Review로 이어집니다' "$HTML_FILE"
grep -q '검증이 통과하면 기본적으로 <code>mansu-5review</code>로 이어지고' "$HTML_FILE"
grep -q '산출물: review handoff' "$HTML_FILE"
grep -q '산출물: slice table' "$HTML_FILE"
grep -q '산출물: 구현/검증 기록' "$HTML_FILE"
grep -q 'aria-pressed="true"' "$HTML_FILE"
! grep -q '상황에 맞게 strict 또는 lite로 구현한다' "$HTML_FILE"
! grep -q 'Project memory / lifecycle' "$HTML_FILE"
! grep -q 'Implementation actor' "$HTML_FILE"
! grep -q '작은 용어 사전' "$HTML_FILE"
grep -q '<h2>Mansu Skill</h2>' "$HTML_FILE"
grep -q '사용자가 직접 부르는 최상위 Mansu 스킬입니다' "$HTML_FILE"
grep -q 'mansu-help' "$HTML_FILE"
grep -q 'mansu-setup' "$HTML_FILE"
grep -q 'mansu-project-start' "$HTML_FILE"
grep -q 'mansu-tdd-total' "$HTML_FILE"
grep -q 'mansu-debug-rootcause' "$HTML_FILE"
grep -q 'mansu-web-verify' "$HTML_FILE"
grep -q 'mansu-ship-release' "$HTML_FILE"
grep -q 'mansu-source-curator' "$HTML_FILE"
grep -q 'Ouroboros routes' "$HTML_FILE"
grep -q 'skills/resume-session' "$HTML_FILE"
grep -q 'gstack, Ouroboros, Oh My, agent-skills, Open Design, 디자인 레퍼런스를 원천별로 묶고' "$HTML_FILE"
grep -q 'gstack-design-shotgun' "$HTML_FILE"
grep -q 'gstack-setup-gbrain' "$HTML_FILE"
grep -q 'Oh My / OMO / OMC routes' "$HTML_FILE"
grep -q 'ultrawork' "$HTML_FILE"
grep -q 'addyosmani/agent-skills' "$HTML_FILE"
grep -q 'frontend-ui-engineering' "$HTML_FILE"
grep -q 'shipping-and-launch' "$HTML_FILE"

for skill_dir in "$ROOT_DIR"/mansu-*; do
  [ -d "$skill_dir" ] || continue
  skill_name="$(basename "$skill_dir")"
  [ "$skill_name" = "mansu-setting" ] && continue
  grep -q "$skill_name" "$HTML_FILE"
  grep -q "id=\"$skill_name\"" "$HTML_FILE"
done

grep -q '| `mansu-0manual` |' "$README_FILE"
grep -q 'docs/mansu-manual.html' "$README_FILE"
grep -q 'scripts/validate_mansu_manual.sh' "$README_FILE"

echo "mansu-manual structure OK"
