#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FILE="$ROOT_DIR/mansu-tdd-total/SKILL.md"
OPENAI_YAML="$ROOT_DIR/mansu-tdd-total/agents/openai.yaml"

test -f "$FILE"
test -f "$OPENAI_YAML"

grep -q '^## Core promise$' "$FILE"
grep -q '^## Shared invariants$' "$FILE"
grep -q '^## What this skill does not do$' "$FILE"
grep -q '^## Preflight$' "$FILE"
grep -q '^## Planning gate$' "$FILE"
grep -q '^## Required planning roles$' "$FILE"
grep -q '^## Real critic agent gate$' "$FILE"
grep -q '^## Oh My execution-mode mapping$' "$FILE"
grep -q '^## Gstack gate mapping$' "$FILE"
grep -q '^## Execution-ready plan requirements$' "$FILE"
grep -q '^## Planning loop$' "$FILE"
grep -q '^## Dispatch rules$' "$FILE"
grep -q '^## Slice table$' "$FILE"
grep -q '^## Execution handoff$' "$FILE"
grep -q '^## Sequential slice gate$' "$FILE"
grep -q '^## Mode-change rules$' "$FILE"
grep -q '^## Closeout$' "$FILE"

grep -q 'mansu-tdd-lite' "$FILE"
grep -q 'mansu-tdd-strict' "$FILE"
grep -q 'PLAN.md' "$FILE"
grep -q '개발일지.md' "$FILE"
grep -q 'per-slice mode' "$FILE"
grep -q 'End-to-end dispatcher, planner, and completion orchestrator' "$FILE"
grep -q 'Execute every unblocked slice in order through the selected skill' "$FILE"
grep -q 'Persist in a Ralph-style loop until all slices are closed' "$FILE"
grep -q 'Run final project-level verification, worklog update, and commit accounting' "$FILE"
grep -q 'remains responsible for making sure the overall workflow actually finishes' "$FILE"
grep -q 'clear execution modes used by this workflow' "$FILE"
grep -q 'persistence loop: `ralph`' "$FILE"
grep -q 'strict TDD habit: `tdd`' "$FILE"
grep -q 'Use `ralph` as the persistence rule for the whole workflow' "$FILE"
grep -q 'Use `tdd` only inside slices routed to `mansu-tdd-strict`' "$FILE"
grep -q 'Do not use parallel Oh My modes such as `ultrawork` or `ultrapilot`' "$FILE"
grep -q "Mansu's default implementation gates come from the gstack family" "$FILE"
grep -q 'Use these core gstack skills by name when they are installed' "$FILE"
grep -q 'review gate: `gstack-review`' "$FILE"
grep -q 'QA evidence without fixes: `gstack-qa-only` or `gstack-browse`' "$FILE"
grep -q 'QA test-fix-verify loop when fixes are approved: `gstack-qa`' "$FILE"
grep -q 'checkpoint/state handoff: `gstack-context-save` and `gstack-context-restore`' "$FILE"
grep -q '`gstack-checkpoint` only when the installed runtime still exposes it' "$FILE"
grep -q 'health gate: `gstack-health`' "$FILE"
grep -q 'Optional escalation gates:' "$FILE"
grep -q 'use `gstack-cso` only when the slice changes auth' "$FILE"
grep -q 'use `gstack-benchmark` only when the slice can affect loading' "$FILE"
grep -q 'Do not run `gstack-ship` from this TDD loop by default' "$FILE"
grep -q 'map the concrete gstack' "$FILE"
grep -q 'A builder saying "I reviewed it" is not enough' "$FILE"
grep -q 'Do not duplicate executor details' "$FILE"
grep -q 'Escalate from lite to strict' "$FILE"
grep -q 'Do not use `lite` as permission to lower work quality' "$FILE"
grep -q 'Treat missing review, QA, checkpoint, worklog, or commit evidence as an open slice' "$FILE"
grep -q 'The only core difference is the RED test requirement' "$FILE"
grep -q 'Do not start the next slice until the current slice is fully closed' "$FILE"
grep -q 'Commit policy:' "$FILE"
grep -q 'Default to per-slice commits during implementation' "$FILE"
grep -q 'Use a final release/docs commit only for final docs' "$FILE"
grep -q 'record the no-commit reason' "$FILE"
grep -q 'Execute slices in order unless the user explicitly approves a different dependency-free order' "$FILE"
grep -q 'A slice is fully closed only when' "$FILE"
grep -q 'Do not start slice N+1 while slice N is open' "$FILE"
grep -q 'do not treat planning as a single-agent TODO list' "$FILE"
grep -q 'Planner: draft the plan' "$FILE"
grep -q 'Critics: challenge the plan' "$FILE"
grep -q 'Synthesizer: merge critique into one execution-ready plan' "$FILE"
grep -q 'runtime-neutral orchestration' "$FILE"
grep -q 'current runtime session' "$FILE"
grep -q 'runtime-backed helper' "$FILE"
grep -q 'When actual multi-agent or helper-session critique is available' "$FILE"
grep -q 'Local role separation is only a fallback' "$FILE"
grep -q 'Record the reason when using the fallback' "$FILE"
grep -q 'real critic agents, helper sessions, or external critique tools' "$FILE"
grep -q 'historical agent names or tools are unavailable' "$FILE"
grep -q 'strict prerequisites are unavailable in the current runtime' "$FILE"
grep -q 'record the mapping in `PLAN.md`' "$FILE"
grep -q 'Do not lock the execution-ready plan or start implementation while an expected critic is still pending' "$FILE"
grep -q 'If a critic fails or times out' "$FILE"
grep -q 'Do not proceed to implementation until the execution-ready plan and slice table are visible' "$FILE"
grep -q 'continue automatically unless the user explicitly requested' "$FILE"
grep -q 'domain language and DDD-style responsibility boundaries' "$FILE"
grep -q 'architecture and module boundaries' "$FILE"
grep -q 'pre-refactor and file/module split plan' "$FILE"
grep -q 'source skills or tools to use' "$FILE"
grep -q 'Oh My execution-mode mapping: `ralph` for persistence and `tdd` for strict slices' "$FILE"
grep -q 'gstack gate mapping: concrete names for `gstack-review`, `gstack-qa-only`/`gstack-browse`, `gstack-qa`, `gstack-context-save`/`gstack-context-restore`, and `gstack-health`, or their current-runtime equivalents' "$FILE"
grep -q 'code construction router' "$FILE"
grep -q 'source skill to read' "$FILE"
grep -q 'CODE_CONSTRUCTION_ORDER.md' "$FILE"
grep -q 'construction router notes' "$FILE"
grep -q 'execution readiness status' "$FILE"
grep -q 'must be separately invoked, produce' "$FILE"
grep -q 'upstream source-of-truth artifacts and paths' "$FILE"
grep -q 'locked decisions and open-question carryover' "$FILE"
grep -q 'upstream artifact or decision this slice implements' "$FILE"
grep -q 'Oh My execution mode: `ralph` persistence plus `tdd` only when strict RED/GREEN/REFACTOR is selected' "$FILE"
grep -q 'gstack gate path: which named gstack skills or current-runtime equivalents close this slice' "$FILE"
grep -q 'gstack-review -> gstack-qa-only or gstack-qa -> gstack-context-save -> commit' "$FILE"
grep -q 'Map the Planner, Critics, and Synthesizer roles' "$FILE"
grep -q 'wait for them or record a real failure/timeout fallback' "$FILE"
grep -q 'Record the role mapping, critic status, execution-ready plan' "$FILE"
grep -q 'Start execution automatically after the plan gate passes' "$FILE"
grep -q 'Continue the sequential slice loop until every unblocked slice is closed' "$FILE"
grep -q 'Run final closeout verification and commit accounting' "$FILE"
grep -q 'pre-refactor notes' "$FILE"
grep -q 'After each delegated slice returns' "$FILE"
grep -q 'Ralph-style persistence means retrying or re-routing reasonable failures' "$FILE"
grep -q 'run the project-level build/test/type/lint suite' "$FILE"
grep -q 'run final QA or browser verification' "$FILE"
grep -q 'run a final diff review or equivalent project review gate' "$FILE"
grep -q 'create a final release/docs commit only when final docs' "$FILE"
grep -q 'if per-slice commits were skipped or deferred, create the final implementation commit' "$FILE"
grep -q 'what could not be verified, remaining risks, and any follow-up checks needed' "$FILE"

grep -q 'short_description: "End-to-end TDD orchestrator that plans, slices, executes, and verifies"' "$OPENAI_YAML"
grep -q 'default_prompt: "Use \$mansu-tdd-total end to end' "$OPENAI_YAML"
grep -q 'prefer real critic agents when available' "$OPENAI_YAML"
grep -q 'map the required Oh My modes ralph and tdd plus core gstack gates' "$OPENAI_YAML"
grep -q 'gstack-review, gstack-qa-only/gstack-browse, gstack-qa, gstack-context-save/restore, and gstack-health' "$OPENAI_YAML"
grep -q 'run every unblocked slice sequentially through the mapped gates plus commit' "$OPENAI_YAML"
grep -q 'project-level verification, final commit accounting, remaining risks, and follow-up checks' "$OPENAI_YAML"

if grep -q 'Hermes/OpenCode orchestration' "$FILE" || grep -q 'Hermes + OpenCode session' "$FILE"; then
  echo "mansu-tdd-total should stay runtime-neutral" >&2
  exit 1
fi

if grep -q '^### RED$' "$FILE" || grep -q '^### GREEN$' "$FILE" || grep -q '^### REFACTOR$' "$FILE"; then
  echo "mansu-tdd-total should not copy strict executor internals" >&2
  exit 1
fi

echo "mansu-tdd-total structure OK"
