#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

for skill in define plan build verify review debug ship; do
  test -f "$ROOT_DIR/mansu-$skill/SKILL.md"
  test -f "$ROOT_DIR/mansu-$skill/agents/openai.yaml"
  grep -q "name: mansu-$skill" "$ROOT_DIR/mansu-$skill/SKILL.md"
  grep -q 'SOURCE_SKILL_COMPOSITION.md' "$ROOT_DIR/mansu-$skill/SKILL.md"
done

grep -q 'interview-me' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'Ouroboros' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q '^## Mandatory Ouroboros definition rule$' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'Do not present Ouroboros interview as an' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'User-provided idea notes do not satisfy the interview gate' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'treat that text as seed context for' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'do not mark Define complete, jump to planning, or replace' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'Skipping the Ouroboros interview is allowed only when current, repo-visible' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'route to `mansu-9setup` in `install` mode' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q '`mansu-9setup` in `update` mode' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'Ouroboros setup blocked reason:' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'Do not silently replace Ouroboros interview with Mansu-owned questions' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'office-hours' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'AGENTS.md' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'CODING_RULES.md' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'If Define is complete, tell the user the next step is .*`mansu-2plan`' "$ROOT_DIR/mansu-define/SKILL.md"
grep -q 'if complete, tell the user to use .*mansu-2plan next' "$ROOT_DIR/mansu-define/agents/openai.yaml"
grep -q 'discover and use Ouroboros interview first' "$ROOT_DIR/mansu-define/agents/openai.yaml"
grep -q 'Treat a user-written one-line, three-line, feature-list, or short product brief as seed context' "$ROOT_DIR/mansu-define/agents/openai.yaml"
grep -q 'treat short user idea notes as seed context for Ouroboros interview' "$ROOT_DIR/mansu-1define/agents/openai.yaml"
grep -q 'route to mansu-9setup in install mode' "$ROOT_DIR/mansu-define/agents/openai.yaml"
grep -q 'route to mansu-9setup in update mode' "$ROOT_DIR/mansu-define/agents/openai.yaml"

grep -q 'Requirements/Spec -> Architecture -> Design Direction -> Implementation Roadmap' "$ROOT_DIR/mansu-plan/SKILL.md"
grep -q 'environment/dependency setup plan when needed' "$ROOT_DIR/mansu-plan/SKILL.md"
grep -q 'Prefer `uv` for Python' "$ROOT_DIR/mansu-plan/SKILL.md"
grep -q 'Do not add a new `uv` environment just because planning is happening' "$ROOT_DIR/mansu-plan/SKILL.md"
grep -q 'gstack-plan-design-review' "$ROOT_DIR/mansu-plan/SKILL.md"
grep -q 'gstack-design-shotgun' "$ROOT_DIR/mansu-plan/SKILL.md"
grep -q '.omo/plans/\*.md' "$ROOT_DIR/mansu-plan/SKILL.md"
grep -Fq 'explicit active plan support does not make `.omo/*` canonical doctrine' "$ROOT_DIR/mansu-plan/SKILL.md"
grep -q 'If Plan is complete, tell the user the next step is .*`mansu-3build`' "$ROOT_DIR/mansu-plan/SKILL.md"
grep -q 'if complete, tell the user to use .*mansu-3build next' "$ROOT_DIR/mansu-plan/agents/openai.yaml"
grep -q 'prefer uv/.venv when appropriate' "$ROOT_DIR/mansu-plan/agents/openai.yaml"

grep -q 'mansu-tdd-total' "$ROOT_DIR/mansu-build/SKILL.md"
grep -q 'LazyCodex is not a source skill family' "$ROOT_DIR/mansu-build/SKILL.md"
grep -q 'The active plan is a role, not a literal filename' "$ROOT_DIR/mansu-build/SKILL.md"
grep -q '.omo/plans/\*.md' "$ROOT_DIR/mansu-build/SKILL.md"
grep -q 'Before non-trivial implementation, read the active plan and any linked' "$ROOT_DIR/mansu-build/SKILL.md"
grep -q 'roadmap, spec, TDR, or design direction' "$ROOT_DIR/mansu-build/SKILL.md"
grep -q 'update the active phase plan before editing code' "$ROOT_DIR/mansu-build/SKILL.md"
grep -q 'support is explicit active plan path support only' "$ROOT_DIR/mansu-build/SKILL.md"
grep -q 'not canonical doctrine' "$ROOT_DIR/mansu-build/SKILL.md"
grep -q 'If implementation for the active phase is complete, tell the user the next' "$ROOT_DIR/mansu-build/SKILL.md"
grep -q 'End by naming the next route: next .*mansu-3build slice, .*mansu-4verify, or mansu-debug' "$ROOT_DIR/mansu-build/agents/openai.yaml"
grep -q 'Before non-trivial implementation, read the active plan and any linked roadmap/spec/TDR/design direction' "$ROOT_DIR/mansu-build/agents/openai.yaml"

grep -q 'QA evidence' "$ROOT_DIR/mansu-verify/SKILL.md"
grep -q 'Verify proves behavior' "$ROOT_DIR/mansu-verify/SKILL.md"
grep -q 'Use BDD-style evidence' "$ROOT_DIR/mansu-verify/SKILL.md"
grep -q 'Given/When/Then' "$ROOT_DIR/mansu-verify/SKILL.md"
grep -q 'observable pass/fail result' "$ROOT_DIR/mansu-verify/SKILL.md"
grep -q 'If verification passes, run .*`mansu-5review` next by default' "$ROOT_DIR/mansu-verify/SKILL.md"
grep -q 'reporting whether review was run or is the immediate next step' "$ROOT_DIR/mansu-verify/agents/openai.yaml"

grep -q 'Review judges quality' "$ROOT_DIR/mansu-review/SKILL.md"
grep -q 'not QA' "$ROOT_DIR/mansu-review/SKILL.md"
grep -q 'Mansu Review does not invent refactoring judgment by itself' "$ROOT_DIR/mansu-review/SKILL.md"
grep -q 'Use gstack `review` as the primary diff/code review route' "$ROOT_DIR/mansu-review/SKILL.md"
grep -q 'source-skill refactoring/simplification findings' "$ROOT_DIR/mansu-review/SKILL.md"
grep -q 'addyosmani `code-simplification`, or OMO `remove-ai-slops`' "$ROOT_DIR/mansu-review/SKILL.md"
grep -q 'over-complex code, dead code, and AI-slop' "$ROOT_DIR/mansu-review/SKILL.md"
grep -q 'If Review passes and Verify evidence exists, tell the user the next step is' "$ROOT_DIR/mansu-review/SKILL.md"
grep -q '.*mansu-6ship if review passes' "$ROOT_DIR/mansu-review/agents/openai.yaml"
grep -q 'use source review routes such as gstack review' "$ROOT_DIR/mansu-review/agents/openai.yaml"

grep -q 'mansu-debug-rootcause' "$ROOT_DIR/mansu-debug/SKILL.md"
grep -q 'root cause' "$ROOT_DIR/mansu-debug/SKILL.md"

grep -q 'mansu-ship-release' "$ROOT_DIR/mansu-ship/SKILL.md"
grep -q 'ship/hold' "$ROOT_DIR/mansu-ship/SKILL.md"
grep -q 'End the response with a clear ship status' "$ROOT_DIR/mansu-ship/SKILL.md"
grep -q 'End with a clear ship/hold status' "$ROOT_DIR/mansu-ship/agents/openai.yaml"

grep -q 'Generated planning state boundary' "$ROOT_DIR/mansu-operating-model/SKILL.md"
grep -Fq '`.omo/*` is generated planning and evidence state' "$ROOT_DIR/mansu-operating-model/SKILL.md"
grep -q 'not a normal runtime source of truth' "$ROOT_DIR/mansu-operating-model/SKILL.md"
grep -q 'Treat older generated plans as archive after promotion' "$ROOT_DIR/mansu-operating-model/SKILL.md"
grep -Fq '`.omo/plans/*.md` may still be a concrete plan path' "$ROOT_DIR/mansu-operating-model/SKILL.md"
grep -Fq '`.omo/*` is generated planning/evidence state' "$ROOT_DIR/mansu-operating-model/references/DOCUMENT_CREATION_ORDER.md"
grep -q 'archive it in place unless the user explicitly approves deletion' "$ROOT_DIR/mansu-operating-model/references/DOCUMENT_CREATION_ORDER.md"
grep -Fq '`.omo/plans/*.md` remains allowed as an explicit active plan location' "$ROOT_DIR/mansu-operating-model/references/DOCUMENT_CREATION_ORDER.md"
